### ISSUE TITLE
$ref example for `newNormalizer`

### ISSUE THREAD

**Issue by jon49** [AlexeyGrishin/schemasaurus#23]
I'm not quite sure how to get this code working. I want to normalize `E`.

``` js
var s = require('schemasaurus');

var v = s.newNormalizer({
  "A.B": {
    "id": "A.B",
    "type": "object",
    "properties": {
      "c": {
        "type": "string"
      },
      "d": {
        "type": "number"
      }
    },
    "required": [
      "c",
      "d"
    ],
    "additionalProperties": false
  },
  "E": {
    "id": "E",
    "type": "object",
    "properties": {
      "f": {
        "type": "array",
        "items": {
          "$ref": "A.B"
        }
      }
    },
    "required": [
      "f"
    ],
    "additionalProperties": false
  }
});

console.log(v({
    f: [
        {
            c: 1,
            d: '2'
        },
        {
            c: '3',
            d: 4
        }
    ]
}));
```

**Comment by jon49** [comment]
OK, I fixed the code some to be in alignment with the way `schemasaurus` accepts arguments.

``` js
var s = require('schemasaurus');

var v = s.newNormalizer({
  "type": "object",
  "properties": {
    "f": {
      "type": "array",
      "items": {
        "$ref": "#/A.B"
      }
    },
    "additionalProperties": false
  },
  "A.B": {
    "id": "A.B",
    "type": "object",
    "properties": {
      "c": {
        "type": "string"
      },
      "d": {
        "type": "number"
      }
    },
    "required": [
      "c",
      "d"
    ],
    "additionalProperties": false
  }}
);

console.log(v({
    f: [
        {
            c: 1,
            d: '2'
        },
        {
            c: '3',
            d: 4
        }
    ]
}));
```

But when I add a `console.log` like so:

``` js
    step: function (schema, varName, opts) {
        console.log('schema:', schema, varName, opts)
```

I get the following output:

```
schema: { type: 'object',
  properties: 
   { f: { type: 'array', items: [Object] },
     additionalProperties: false },
  'A.B': 
   { id: 'A.B',
     type: 'object',
     properties: { c: [Object], d: [Object] },
     required: [ 'c', 'd' ],
     additionalProperties: false } } val undefined
schema: { type: 'array', items: { '$ref': '#/A.B' } } var4 { attr: undefined }
schema: { '$ref': '#/A.B' } var8 { attr: 'item' }
schema: { id: 'A.B',
  type: 'object',
  properties: { c: { type: 'string' }, d: { type: 'number' } },
  required: [ 'c', 'd' ],
  additionalProperties: false } var8 { attr: 'item' }
schema: { type: 'string' } var13 { attr: undefined }
schema: { type: 'number' } var17 { attr: undefined }
schema: { additionalProperty: false } var22 { attr: undefined }
schema: { '$ref': '#/A.B' } nil { attr: 'item' }
schema: false var29 { attr: undefined }
```

With the following error:

``` error
node : C:\r\mobiledlr\mobiledlr\node_modules\schemasaurus\src\compiler.js:142
At line:2 char:1
+ node .\test.js
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\r\mobiledlr\...compiler.js:142:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

        Object.defineProperty(schema, "$$visited", {value: true, enumerable: f
               ^
TypeError: Object.defineProperty called on non-object
    at Function.defineProperty (native)
    at Object.Compiler.step (C:\r\mobiledlr\mobiledlr\node_modules\schemasaurus\src\compiler.js:142:16)
    at Object.<anonymous> (C:\r\mobiledlr\mobiledlr\node_modules\schemasaurus\src\compiler.js:149:18)
    at Object.SchemaPartProcessor.processProperties 
(C:\r\mobiledlr\mobiledlr\node_modules\schemasaurus\src\int\processor.js:82:18)
    at Object.<anonymous> (C:\r\mobiledlr\mobiledlr\node_modules\schemasaurus\src\int\processor.js:18:20)
    at Array.forEach (native)
    at Object.SchemaPartProcessor.execute 
(C:\r\mobiledlr\mobiledlr\node_modules\schemasaurus\src\int\processor.js:17:25)
    at Object.Compiler.stepProcess (C:\r\mobiledlr\mobiledlr\node_modules\schemasaurus\src\compiler.js:168:24)
    at Object.Compiler.step (C:\r\mobiledlr\mobiledlr\node_modules\schemasaurus\src\compiler.js:146:14)
    at Object.Compiler.compile (C:\r\mobiledlr\mobiledlr\node_modules\schemasaurus\src\compiler.js:197:14)
```

Obviously `false` is not an object.

**Comment by jon49** [comment]
I added the code `|| schema === false` to `compiler.js` on line `136` and now it works perfectly. Not sure why. I don't understand the logic of the code enough to understand all that is going on.

``` js
    step: function (schema, varName, opts) {
        if (schema.$$visited || schema === false) {
```
